### PR TITLE
[17.0][MIG] pydantic: Migration to 17.0

### PR DESCRIPTION
**Pull request by trisdoan**

### CODE REVIEW

**Comment by lmignon** [comment]
Hi @trisdoan

Thank you for the migration. Can you fix the pre-commit error so I can process to the merge?

lmi

**Comment by trisdoan** [comment]
DRAFT: fix failed pre-commit

**Comment by trisdoan** [comment]
Hello @lmignon, all checks are passed, please help to merge it, thanks

**Review by lmignon — APPROVED** [review]
Thank you for this migration

**Pull request merged**
