### PR TITLE
[15.0][MIG] pydantic: Migration to 15.0

### PR DESCRIPTION
**Pull request by yankinmax**
Depends on:
- [ ] https://github.com/OCA/rest-framework/pull/218

### CODE REVIEW

**Comment by yankinmax** [comment]
@lmignon Can you pls approve the running workflow to finish with the checks?

**Comment by gurneyalex** [comment]
@yankinmax can you rebase?

**Comment by gurneyalex** [comment]
@yankinmax  I pushed the last fix from 14.0 on your branch

**Comment by yankinmax** [comment]
> @yankinmax I pushed the last fix from 14.0 on your branch

thanks

**Comment by yankinmax** [comment]
@gurneyalex as I correctly understand we're waiting till pydantic will land into V14, yes?

**Comment by lmignon** [comment]
@yankinmax @gurneyalex The initial PR is now closed. See https://github.com/OCA/rest-framework/pull/218#issuecomment-1028053809 for the motivations. Don't be afraid, the current approach is replaced by a more generic one.

**Comment by lmignon** [comment]
pydantic is now available into 15.0 based on python lib extendable_pydantic

**Comment by yankinmax** [comment]
thanks a lot @lmignon

**Pull request closed without merging**
