### PR TITLE
[13.0] Fix issue with datamodel, recursion limit

### PR DESCRIPTION
**Pull request by lmignon**
Forward port of #120

### CODE REVIEW

**Comment by xu4wang** [comment]
@lmignon we met this issue in V13 today.. just to double confirm the fix is not yet available for V13?

**Comment by xu4wang** [comment]
For a quick and dirty solution, if I just change __getitem__ in datamodel/core.py, according to
https://github.com/OCA/rest-framework/pull/120/files

do you think it will work?

**Comment by lmignon** [comment]
@xu4wang You could use the patch into this PR. That should fix the issue. I'll merge it in the coming days... Unfortunately the env available into the datamodel is not consistent. It's always the one from where a given datamodel was first called... I was hoping to find a solution to this problem before doing a merge of this fix but I haven't found the solution yet.

**Comment by xu4wang** [comment]
> @xu4wang You could use the patch into this PR. That should fix the issue. I'll merge it in the coming days... Unfortunately the env available into the datamodel is not consistent. It's always the one from where a given datamodel was first called... I was hoping to find a solution to this problem before doing a merge of this fix but I haven't found the solution yet.

thanks @lmignon for the confirmation. We will hot patch it first. Looking forward for the updated official V13 version.

**Comment by xu4wang** [comment]
@lmignon I made below changes to core.py

```
    def __getitem__(self, key):
        model = self.registry[key]
        #model.__init__ = functools.partialmethod(model.__init__, env=self.env)
        __initial__init__ = getattr(model, "__initial__init__", None)
        if not __initial__init__:
            __initial__init__ = model.__init__
            setattr(model, "__initial__init__", __initial__init__)  # noqa: B010
        # The env to propagate should always be the one from where we access
        # to the registry. In the same time we must ensure that the patched
        # constructor is the original one and not an already patched one
        model.__init__ = functools.partialmethod(__initial__init__, env=self.env)

        @classmethod
        def __get_schema_class__(cls, **kwargs):
            cls = cls.__schema_class__(**kwargs)
            cls._env = self.env
            return cls

        model.__get_schema_class__ = __get_schema_class__
        return model

```

However, I believe the issue is not fixed, the issue is still happening after a longer running time, although it's relieved.

```
2021-05-20 11:21:00,868 1950 ERROR gateway odoo.addons.base_rest.http: RESTFULL call to url http://gateway.lan:8070/api/v1/redirect/orders/1621275390.0676239?signature=value1&timestamp=value2&provider=Ksher with method GET and params {'provider': 'Ksher', 'signature': 'value1', 'timestamp': 'value2'} raise the following error 500 Internal Server Error: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/Users/wangxu/Documents/github/rest-framework/rest_log/components/service.py", line 37, in _dispatch_with_db_logging
    result = super().dispatch(method_name, *args, params=params)
  File "/Users/wangxu/Documents/github/kshermall/ksher-addons/base_rest/components/service.py", line 160, in dispatch
    res = method(*args, secure_params)
  File "/Users/wangxu/Documents/github/kshermall/ksher-addons/base_rest/restapi.py", line 62, in response_wrap
    response = f(*args, **kw)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/addons/gateway/services/l1_redirect.py", line 83, in query
    return self._build_response(RES_QUERY, res)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/addons/gateway/services/l1_redirect.py", line 115, in _build_response
    r = res(partial=True)
  File "/Users/wangxu/Documents/github/ksher-saas/venv/lib/python3.7/site-packages/marshmallow_objects/models.py", line 81, in __call__
    obj = cls.load(kwargs, many=many, context=context, partial=partial, unknown=unknown,)
  File "/Users/wangxu/Documents/github/ksher-saas/venv/lib/python3.7/site-packages/marshmallow_objects/models.py", line 229, in load
    loaded = schema.load(data, many=many)
  File "/Users/wangxu/Documents/github/ksher-saas/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 726, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/Users/wangxu/Documents/github/ksher-saas/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 900, in _do_load
    partial=partial,
  File "/Users/wangxu/Documents/github/ksher-saas/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 1099, in _invoke_load_processors
    partial=partial,
  File "/Users/wangxu/Documents/github/ksher-saas/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 1225, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "/Users/wangxu/Documents/github/kshermall/ksher-addons/datamodel/core.py", line 97, in __make_object__
    return datamodel(__post_load__=True, __schema__=self, **data)
  File "/Users/wangxu/Documents/github/ksher-saas/venv/lib/python3.7/site-packages/marshmallow_objects/models.py", line 75, in __call__
    obj.__init__(*args, **kwargs)
  File "/Users/wangxu/.pyenv/versions/3.7.7/lib/python3.7/functools.py", line 376, in _method
    return self.func(*call_args, **call_keywords)
  File "/Users/wangxu/.pyenv/versions/3.7.7/lib/python3.7/functools.py", line 376, in _method
    return self.func(*call_args, **call_keywords)
  File "/Users/wangxu/.pyenv/versions/3.7.7/lib/python3.7/functools.py", line 376, in _method
    return self.func(*call_args, **call_keywords)
  [Previous line repeated 934 more times]
  File "/Users/wangxu/.pyenv/versions/3.7.7/lib/python3.7/functools.py", line 372, in _method
    call_keywords = self.keywords.copy()
RecursionError: maximum recursion depth exceeded while calling a Python object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wangxu/Documents/github/kshermall/ksher-addons/base_rest/http.py", line 182, in _handle_exception
    return super(HttpRestRequest, self)._handle_exception(exception)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 750, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "<string>", line 7, in get_query
  File "/Users/wangxu/Documents/github/kshermall/ksher-addons/base_rest/controllers/main.py", line 142, in _process_method
    result = service.dispatch(method_name, *args, params=params)
  File "/Users/wangxu/Documents/github/rest-framework/rest_log/components/service.py", line 31, in dispatch
    return self._dispatch_with_db_logging(method_name, *args, params=params)
  File "/Users/wangxu/Documents/github/rest-framework/rest_log/components/service.py", line 51, in _dispatch_with_db_logging
    RESTServiceDispatchException, orig_exception, *args, params=params
  File "/Users/wangxu/Documents/github/rest-framework/rest_log/components/service.py", line 78, in _dispatch_exception
    raise exception_klass(exc_msg, log_entry_url) from orig_exception
odoo.addons.rest_log.exceptions.RESTServiceDispatchException: maximum recursion depth exceeded while calling a Python object
2021-05-20 11:21:00,873 1950 INFO gateway werkzeug: 127.0.0.1 - - [20/May/2021 11:21:00] "GET /api/v1/redirect/orders/1621275390.0676239?

```

Do you have any suggestion? How shall I isolate the issue and make a quick fix?

BR,Xu

**Comment by xu4wang** [comment]
> @lmignon I made below changes to core.py
> 

@lmignon Sorry, I was wrong. I patched one copy and tested another original un-patched copy.
The patch works.  thank you!

**Comment by farzeni** [comment]
Hi,

I understand the problem with the env inconsistency but I think it could be better than this random recursion error we are experiencing as well. 

Currently we are running with a forked version of rest_framework but this is not ideal. Is there any chance that this PR will be ported to 13.0 until a better solution is found? Or do you think it is better not to rely too much on datamodels until this issue is totally fixed?

I take this opportunity to thank you @lmignon and every contributor for your work on this module!

**Comment by lmignon** [comment]
@farzeni I'll take some times next week to merge this fix and add a comment into the documentation under a limitation section.

**Comment by lmignon** [comment]
@kevinkhao @farzeni  OK for the merge once travis is :green_circle: ?

**Comment by rvalyi** [comment]
@lmignon OK for me too, We use this patch in v12 and v14 all installations otherwise it breaks. Would be cool if we could merge the 12.0 PR too https://github.com/OCA/rest-framework/pull/179 ...

**Comment by lmignon** [comment]
@rvalyi I'll merge the PRs for 12 13 and 14

**Pull request merged**
