### PR TITLE
17.0 mig graphql demo

### PR DESCRIPTION
**Pull request by dduarte-odoogap**

### CODE REVIEW

**Review by ccarrenoc — APPROVED** [review]

**Comment by sbidoul** [comment]
Can you preserve the commit history using the recommended procedure? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

**Comment by sbidoul** [comment]
I was wondering why this PR is green while the dependent `graphql_base` is not merged. But it does not set `graphql_demo` to installable, so that explains.

Could you cherry pick these commits in the `graphql_base` PR so we can test it on runboat?

**Comment by dduarte-odoogap** [comment]
@sbidoul just pushed

**Pull request closed without merging**
