### PR TITLE
[11.0][FIX] Check database existence before initializing it

### LINKED ISSUE #108: Odoo crashes after dropping a database
It might happen that a database is deleted, expecially while developing new features.
If module `base_rest` is installed in at least one DB (even the deleted one), the `get_request` override in `base_rest/http.py` will eventually try to initialize the deleted database without checking if it still exists. So when the `odoo.registry(db)` line is reached, Odoo tries to initialize a Registry for a non existing database, and it crashes.

PRs:

- [ ] 11.0: #109
- [x] 12.0: #110
- [x] 13.0: #111
- [x] 14.0: #112

### PR DESCRIPTION
**Pull request by SilvioGregorini**
Closes #108

### CODE REVIEW

**Review by matteoopenf — APPROVED** [review]

**Comment by lmignon** [comment]
Thank you @SilvioGregorini
We have to fix travis in order to merge your PR.

**Comment by SilvioGregorini** [comment]
@lmignon in the meanwhile, should I open the same PR for other versions of the module (12, 13, 14)?

**Comment by lmignon** [comment]
> @lmignon in the meanwhile, should I open the same PR for other versions of the module (12, 13, 14)?

For sure

**Comment by matteoopenf** [comment]
Is it possible merge?

**Comment by simahawk** [comment]
already merged on next versions but still red here.
@SilvioC2C can you have a look?

**Comment by SilvioC2C** [comment]
@simahawk apparently we're having a dependency conflict issue with `pre-commit`:
```
    The conflict is caused by:
        pylint-odoo 3.5.0 depends on pylint==2.5.3; python_version >= "3"
        pylint-plugin-utils 0.6 depends on pylint>=1.7
        pre-commit-dummy-package 0.0.0 depends on pylint==2.3.1
    
    To fix this you could try to:
    1. loosen the range of package versions you've specified
    2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Pull request closed without merging**
