### PR TITLE
[14.0] [IMP] base_rest: support multiple types

### PR DESCRIPTION
**Pull request by renda-dev**
The main goal for this PR is to add multi-type support when generating swagger docs.

At the current state, even tho cerberus validator supports multi-type validation, swagger would raise an error without giving access to the api's docs.

To do so, I've also updated Swagger UI and OpenAPI to the LTS.

Depends on #417

### CODE REVIEW

**Review by lmignon — CHANGES_REQUESTED** [review]
@renda-dev Thank you for the improment. Can you fix the tests plz?

**Comment by renda-dev** [comment]
> @renda-dev Thank you for the improment. Can you fix the tests plz?

Greetings, `base_rest`'s test have been fixed, while `fastapi`'s tests are still broken, even tho that module has been left untouched.

Is it possible to keep going with this PR anyway? @lmignon

**Comment by HekkiMelody** [comment]
It's my understanding that https://github.com/OCA/rest-framework/pull/417 is required for this PR's tests to pass, is that correct?

**Comment by renda-dev** [comment]
> It's my understanding that #417 is required for this PR's tests to pass, is that correct?

Yes it is. @aleuffre

**Comment by lmignon** [comment]
@renda-dev #417 is on its path to be merged. Once merged can you rebase your PR to make it :green_circle:

**Comment by renda-dev** [comment]
> @renda-dev #417 is on its path to be merged. Once merged can you rebase your PR to make it 🟢

Done, thanks! @lmignon

**Review by lmignon — APPROVED** [review]
LGTM (Code review only)

**Review by HekkiMelody — APPROVED** [review]
Code and functional review. We've been using this in production for a few weeks now.

**Pull request merged**
