### PR TITLE
fix args order mistake when the path has multi path arguments,

### PR DESCRIPTION
**Pull request by moebiusever**
eg.,rule with "/path/<string:in1>/<string:in2>" ,
path with /path/1/2,
will get in2=1, in1=2 with mistake sometimes
becuase the rule.arguments is type of set which was not ordered,
after fix, will always got in1=1, in2=2

### CODE REVIEW

**Comment by etobella** [comment]
The error was solved with this https://github.com/OCA/rest-framework/pull/148 but it was never merged...

**Comment by lmignon** [comment]
@etobella I prefer this far less intrusive approach proposed into this PR

**Comment by etobella** [comment]
Well, I don't know if this really solves the issue, it might be. However, my PR fixed the approach, that it might be improved IMO. Logic was complicated in order to remove problems on existing installations, but it could be simplified in a newer version.

**Comment by lmignon** [comment]
@etobella I prefer to not merge your pr since it adds a lot of complexity for an issue that can be fixed in 1 line change.

**Comment by lmignon** [comment]
@moebiusever Welcome into the community. Thank you for the fix. Can you sign the Contributor License Agreement so we can proceed with the merge.

Regards

**Comment by etobella** [comment]
@lmignon This is a patch, my solution is a fix and improvement. It is right for me if you prefer to patch it. However, the real error is still there...

My point is, the patch is still using arguments, we should use kwargs.

**Review by lmignon — APPROVED** [review]

**Comment by moebiusever** [comment]
> @moebiusever Welcome into the community. Thank you for the fix. Can you sign the Contributor License Agreement so we can proceed with the merge.
> 
> Regards

@lmignon  Hello,  I‘ve signed it and sent to cla AT odoo-community.org. Sorry for my poor english.

**Comment by lmignon** [comment]
@moebiusever your commit 2a81ec271f9037010c11203c7f327528d6a0ee46 has been merged in #264 The other one change the current behavior without motivation. I close this PR. Thank you for the fix

**Pull request closed without merging**
