### PR TITLE
[MIG] model_serializer: Migration to 15.0

### PR DESCRIPTION
**Pull request by fdegrave**
GenericMinimalSerializer had to be adapted since it made use of the "id" and "display_name" field definitions on the "base" model. But since 15.0 those magic fields are not defined on abstract models anymore (therefore not on "base"), but they are added dynamically when the model class is created through the metaclass.

In order to work around the issue the simplest solution was to explicitly define the "id" and "display_name" marshmallow fields in GenericMinimalSerializer.

### CODE REVIEW

**Comment by fdegrave** [comment]
Hi @lmignon,I guess no one will merge this since there is no maintainer for this module. Should I set myself as the maintainer?

**Comment by lmignon** [comment]
@fdegrave You're welcome to become the maintainer...

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
@fdegrave Once you've put yourself as maintainer, I'll merge your PR. (ping me once it's done)

**Comment by fdegrave** [comment]
@lmignon whenever you have time! Thanks

**Review by lmignon — APPROVED** [review]

**Pull request merged**
