### PR TITLE
[15.0][MIG] datamodel: Migration to 15.0

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Comment by yankinmax** [comment]
Got Errors on tests runing with pytest
```
_______________________ ERROR at setup of TestRegistryAccess.test_registry_access _______________________

cls = <class 'odoo.addons.datamodel.tests.test_build_datamodel.TestRegistryAccess'>

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
>       cls.setUpDatamodel()

odoo/external-src/rest-framework/datamodel/tests/common.py:72: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
odoo/external-src/rest-framework/datamodel/tests/common.py:36: in setUpDatamodel
    builder = env["datamodel.builder"]
odoo/src/odoo/api.py:533: in __getitem__
    return self.registry[model_name]._browse(self, (), ())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <odoo.modules.registry.Registry object at 0x7f0e31b74d30>, model_name = 'datamodel.builder'

    def __getitem__(self, model_name):
        """ Return the model with the given name or raise KeyError if it doesn't exist."""
>       return self.models[model_name]
E       KeyError: 'datamodel.builder'

odoo/src/odoo/modules/registry.py:181: KeyError
=============================================== FAILURES ================================================
________________________________ TestBuildDatamodel.test_add_inheritance ________________________________
odoo/external-src/rest-framework/datamodel/tests/common.py:151: in setUp
    env["datamodel.builder"].build_registry(
odoo/src/odoo/api.py:533: in __getitem__
    return self.registry[model_name]._browse(self, (), ())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <odoo.modules.registry.Registry object at 0x7f0e31b74d30>, model_name = 'datamodel.builder'

    def __getitem__(self, model_name):
        """ Return the model with the given name or raise KeyError if it doesn't exist."""
>       return self.models[model_name]
E       KeyError: 'datamodel.builder'

odoo/src/odoo/modules/registry.py:181: KeyError
```
Same for all tests. Can somebody help pls?

**Comment by lmignon** [comment]
@yankinmax No time to debug, sorry. You should take a look at #218. odoo.addons.pydantic is far more powerfull and easier than datamodel. Moreover the way I implmented the extension capabilities of an existing pydantic model is more pythonic and allows type checking. No more need to get access to a registry to retrieve a model, you simply use your pydantic class as any common python class.

**Review by lmignon — CHANGES_REQUESTED** [review]
@yankinmax datamodels is not declared as `installable` https://github.com/yankinmax/rest-framework/blob/15.0-mig-datamodel/datamodel/__manifest__.py#L19

**Comment by yankinmax** [comment]
> @yankinmax datamodels is not declared as `installable` https://github.com/yankinmax/rest-framework/blob/15.0-mig-datamodel/datamodel/__manifest__.py#L19

Does it change installable to False when using the migration procedure?
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by yankinmax** [comment]
@lmignon can you pls take a look again here? It seems to be ok.

**Review by lmignon — APPROVED** [review]

**Comment by yankinmax** [comment]
@lmignon AFAIU @simahawk restarted the build and check passed. See here https://github.com/OCA/server-auth/pull/310#issuecomment-982704257

**Pull request merged**
