### PR TITLE
[13.0][FIX] base_rest: correct external-dependency

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Use correct name, the one that is in requirements.

### CODE REVIEW

**Review by lmignon — APPROVED** [review]

**Review by lmignon — CHANGES_REQUESTED** [review]
@MiquelRForgeFlow Thank you for the change. In the same time could you remove the corresponding line into the dependencies override of the setup.py file https://github.com/OCA/rest-framework/blob/13.0/setup/base_rest/setup.py#L8

**Comment by MiquelRForgeFlow** [comment]
Done. Should I do the same for 12.0 and 11.0 branches?

**Comment by sbidoul** [comment]
No this only works in 13 and later.

**Pull request merged**
