### PR TITLE
[15.0][MIG] base_rest_auth_api_key: Migration to 15.0

### PR DESCRIPTION
**Pull request by yankinmax**
Depends on:
- [x] https://github.com/OCA/rest-framework/pull/225

### CODE REVIEW

**Comment by yankinmax** [comment]
@lmignon Can you pls take a look here?

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by simahawk — COMMENTED** [review]
LG

**Review by lmignon — CHANGES_REQUESTED** [review]
@yankinmax Can you remove your last commit since all the required dependencies are now merged

**Comment by yankinmax** [comment]
> @yankinmax Can you remove your last commit since all the required dependencies are now merged

rebased

**Review by lmignon — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Pull request merged**
