### PR TITLE
[16.0] fastapi:  optionally authenticated partner

### PR DESCRIPTION
**Pull request by lmignon**

### CODE REVIEW

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)

**Review by simahawk — APPROVED** [review]
LG

**Review by qgroulard — APPROVED** [review]

**Comment by lmignon** [comment]
@dreispt we should not merge this one....I should have put this PR in draft because I still want to check something. On further thought, the approach doesn't seem right. I'll revert it

**Pull request merged**
