### PR TITLE
[WIP] [16.0] base_rest

### PR DESCRIPTION
**Pull request by Nikul-OSI**

### CODE REVIEW

**Comment by dreispt** [comment]
Thank you Nikul.
Is this ready for review?
Why are tests failing?

**Comment by dreispt** [comment]
PS: and please squash your commits. Thank you.

**Comment by Nikul-OSI** [comment]
Hello @dreispt , Yes it's ready for review.
Travis failed because odoo version in pre-commit file.
```
ERROR: Could not find a version that satisfies the requirement odoo-addon-component<16.1dev,>=16.0dev (from versions: 15.0.1.0.0.2, 15.0.1.0.0.3, 15.0.1.0.1, 15.0.1.0.2)
ERROR: No matching distribution found for odoo-addon-component<16.1dev,>=16.0dev

```

**Comment by StefanRijnhart** [comment]
~~Please use the technical method described in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#how-to to preserve the full history.~~ Oh nevermind :smile:

**Comment by StefanRijnhart** [comment]
Hi Nikul, our paths cross again. I found your work on Friday and I tried to improve on it but I did not manage to fully deliver it. I've left it here as work in progress just for reference: https://github.com/OCA/rest-framework/pull/313

I'm finding this very difficult, I must say! Maybe we can keep in touch about the remaining issues?

**Comment by StefanRijnhart** [comment]
Let's continue on #313

**Pull request closed without merging**
