### PR TITLE
[16][FIX] fastapi: Compatibility with latest Odoo

### LINKED ISSUE #414: [16.0] fastapi error on request
## Module
fastapi

## Describe the bug
Error on request:
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 2044, in __call__
    response = request._serve_db()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1633, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1660, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/custom/src/rest-framework/fastapi/fastapi_dispatcher.py", line 22, in dispatch
    environ = self._get_environ()
  File "/opt/odoo/custom/src/rest-framework/fastapi/fastapi_dispatcher.py", line 46, in _get_environ
    environ["wsgi.input"] = self.request.httprequest._get_stream_for_parsing()
AttributeError: 'HTTPRequest' object has no attribute '_get_stream_for_parsing'

## To Reproduce
**Affected versions**: 16.0

1.Install fastapi
2.Configure any endpoint
3.Try to use the endpoint via request/swagger

**Additional context**
Debian
Doodba
Python 3.10

### PR DESCRIPTION
**Pull request by lmignon**
From https://github.com/odoo/odoo/commit/cb1d057dcab28cb0b0487244ba99231ee292502e, the orignal werkzeug request is wrapped in a dedicated class to keep under control the attributes developers use. This change add code to make the fastapi addon working with version including this last change and prior version

fixes #414

### CODE REVIEW

**Review by Tscunami — APPROVED** [review]
Reviewed the changes and the issue with the Odoo module has been resolved on Odoo.sh for version 16.0 latest. The solution implemented in this pull request effectively addresses the problem I encountered. Great work, and thank you for the quick turnaround!

**Review by florian-dacosta — APPROVED** [review]
LGTM code review + tests (with old + newest version of Odoo to test both compatibility)
Thanks for the fast fix Laurent

**Review by bealdav — APPROVED** [review]
LGTM

**Comment by bealdav** [comment]
I suppose it might merged as quick fix ?

**Review by JanQubiQ — APPROVED** [review]
LGTM

**Comment by lmignon** [comment]
@florian-dacosta Can you test-it again on latest odoo? runbaoat seems to have some trouble. On old version it works (tested on my project).

**Comment by florian-dacosta** [comment]
I have just re-tested the latest version of this PR with the latest version of Odoo on my project and it works fine.

**Comment by lmignon** [comment]
Thank you to all for the tests and reviews.

**Pull request merged**
