### PR TITLE
[14.0] fwd port of PR #147

### PR DESCRIPTION
**Pull request by Mat-moran**
Fordward port of PR #147 by @simahawk 

I only add their changes to 14.0.

See atomic commits for details.

Most important change: you can now selectively enable logging by:

`collection_name` # enable for all endpoints of the collection
`collection_name.usage` # enable for specific endpoints
`collection_name.usage.endpoint` # enable for specific endpoints
`collection_name*:state` # enable only for specific state (success, failed)

### CODE REVIEW

**Review by simahawk — CHANGES_REQUESTED** [review]
@Mat-moran seems you are losing ownership of commits. Are you following this guide? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0
You should use format-patch so that you pick all the commits that we miss here w/ ownership preserved.

**Comment by Mat-moran** [comment]
Sorry @simahawk my first PR...

I am following the guidelines in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

when I do the command `git format-patch --keep-subject --stdout origin/14.0..origin/13.0 -- rest_log | git am -3 --keep
` I get the next error with a patch
```
Applying: rest_log: improve logging active conf
Using index info to reconstruct a base tree...
M	rest_log/components/service.py
M	rest_log/models/rest_log.py
M	rest_log/tests/test_db_logging.py
Falling back to patching base and 3-way merge...
Auto-merging rest_log/tests/test_db_logging.py
Auto-merging rest_log/models/rest_log.py
CONFLICT (content): Merge conflict in rest_log/models/rest_log.py
Auto-merging rest_log/components/service.py
error: Failed to merge in the changes.
Patch failed at 0001 rest_log: improve logging active conf
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

But I am not trying to migrate from 13.0 to 14.0 because the module is already in v14.0. I need only apply the changes you did in v13.0 to v14.0.

**Comment by Mat-moran** [comment]
@simahawk sorry I did not follow the guide it is my first PR. 
I have a new updated repo, I think I am going to create a new PR and delete this one. Is that OK for you?

**Comment by simahawk** [comment]
you can keep this branch and PR. Just do this:
```
git reset --hard OCA/14.0
git format-patch --keep-subject --stdout OCA/14.0..OCA/13.0 -- base_rest | git am -3 --keep
git format-patch --keep-subject --stdout OCA/14.0..OCA/13.0 -- rest_log | git am -3 --keep
```
check it's all good and run tests
```
git push -f
```
This will cherry-pick all commits from 13.0, only the missing ones (does not matter if it is a full migration or not).

**Comment by Mat-moran** [comment]
Thank  @simahawk for the explanation and instructions.

I did not have OCA/14.0 because I did a fork... but I add OCA as a new upstream and I did what you suggested, to cherry pick the your commits ( a much more intelligent and easy approach that rewrite all of them :smile: thanks for the tip ).

I hope everithing now will be ok.

**Comment by simahawk** [comment]
please check the build

**Comment by Mat-moran** [comment]
Sorry @simahawk  I have been very busy this weeks and asi have to configure the enviroment to do the local test I was postposing this task. I see you did the migration.

Thanks a lot.
Regards

**Pull request closed without merging**
