### PR TITLE
[16.0] Update project template

### PR DESCRIPTION
**Pull request by lmignon**
* Uses ruff to check and format code
* Uses pyproject.toml files in addition to the setup directory

### CODE REVIEW

**Comment by sbidoul** [comment]
Weird error. I'll look into this.

**Comment by sbidoul** [comment]
It's a PYTHONPATH issue creating confusion because `import types` unexpectedly imports `types.py` at the root of the graphql_base addon. I'll investigate. It might be a bug in `build`, not sure.

**Comment by sbidoul** [comment]
Should be fixed when https://github.com/OCA/oca-github-bot/pull/270 is deployed.

**Comment by lmignon** [comment]
> Should be fixed when [OCA/oca-github-bot#270](https://github.com/OCA/oca-github-bot/pull/270) is deployed.

great! Thank you.

**Pull request closed without merging**
