### PR TITLE
[10.0][UPD] Update base_rest module logo

### PR DESCRIPTION
**Pull request by lmignon**
backport of #40

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Not sure what has happened with CLA, as the partner was there with the tag. I'll check and tell you back...

**Comment by lmignon** [comment]
No stress @pedrobaeza Thank you for the support.

**Comment by pedrobaeza** [comment]
OK, I see the problem: the registered email is not the same (not showing it due to GDPR privacy question, but it's a gmail one).

@marcelsavegnago should we switch the email address to the new one?

**Pull request closed without merging**
