### PR TITLE
[16.0] [FIX] fastapi: Unflag save_session in routing info

### PR DESCRIPTION
**Pull request by paradoxxxzero**
This is as much a PR as a question.

Is there any reason to not set the `save_session` to False and thus remove the `session_id` cookie? 

FYI: @sebastienbeau

### CODE REVIEW

**Comment by lmignon** [comment]
> This is as much a PR as a question.
> 
> Is there any reason to not set the `save_session` to False and thus remove the `session_id` cookie?

by ignorance ...

**Review by lmignon — APPROVED** [review]
it makes sense

**Comment by sbidoul** [comment]
Does this have backward compatibility implications?

**Comment by paradoxxxzero** [comment]
Not that I know of, the session should not be used in the api.

**Review by flotho — APPROVED** [review]
Make sense,
LGTM

**Comment by lmignon** [comment]
We could make it configurable on the endpoint.

**Comment by sbidoul** [comment]
I think there are people who use regular Odoo users to authenticate REST APIs. There were PR to that end for base_rest in the past, IIRC. So if this influences such use cases (I'm not sure myself), it's probably necessary to make it configurable.

**Comment by sebastienbeau** [comment]
@sbidoul @lmignon I think we can start by just add this default value. Then in your custom you can still inherit the method "_get_routing_info" to change the value and also to change the "auth" params to use native odoo authentification

**Comment by lmignon** [comment]
> @sbidoul @lmignon I think we can start by just add this default value. Then in your custom you can still inherit the method "_get_routing_info" to change the value and also to change the "auth" params to use native odoo authentification

https://github.com/akretion/rest-framework/pull/7 :smirk:

**Comment by paradoxxxzero** [comment]
Merged (and linted :p)

**Review by sbidoul — APPROVED** [review]

**Pull request merged**
