### PR TITLE
[16.0][FIX] fastapi: always add authenticate_partner_id in context when evaluating ir rules

### PR DESCRIPTION
**Pull request by AnizR**
This fix is needed due to a modificiation of ir.rule that checks the domain when creating/modifying ir rules:

https://github.com/odoo/odoo/commit/91a356628e2878798bc2ff64af5c3fb3a6b3718c

The solution is to set authenticate_partner_id by default to False when it is not present in context

### CODE REVIEW

**Review by adrienpeiffer — APPROVED** [review]
Code review

**Comment by adrienpeiffer** [comment]
@sbidoul @lmignon

**Review by espo-tony — APPROVED** [review]
:+1:

**Review by astirpe — APPROVED** [review]

**Review by sbidoul — APPROVED** [review]
Looks good. Last word to @lmignon, though.

**Comment by lmignon** [comment]
@AnizR Can you add a file named `410.bugfix` into the `fastapi/readme/newsfragments` directory. The content of this file will be used to fill the module's change log. It should therefore provide a short description of this PR to help users to know in an easy way the changes made between versions.

**Comment by AnizR** [comment]
> @AnizR Can you add a file named `410.bugfix` into the `fastapi/readme/newsfragments` directory. The content of this file will be used to fill the module's change log. It should therefore provide a short description of this PR to help users to know in an easy way the changes made between versions.

Done :+1:

**Pull request merged**
