### PR TITLE
[12.0][UPD] Update base_rest module logo

### PR DESCRIPTION
**Pull request by marcelsavegnago**
- Update base_rest module logo

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why changing color?

**Comment by marcelsavegnago** [comment]
@pedrobaeza Since I didn't have the SVG file I created a new one and tried to follow the same color pattern. But I think it got a little darker. In this case the icon size is smaller than the other modules.

**Comment by lmignon** [comment]
@marcelsavegnago Can you preserve the initial colors PLZ.

**Comment by lmignon** [comment]
Thank you @marcelsavegnago Your last changes LGTM. Nevertheless could you sign the CLA so I can merge your changes?

**Comment by marcelsavegnago** [comment]
> Thank you @marcelsavegnago Your last changes LGTM. Nevertheless could you sign the CLA so I can merge your changes?

@lmignon Ok

**Comment by marcelsavegnago** [comment]
> > Thank you @marcelsavegnago Your last changes LGTM. Nevertheless could you sign the CLA so I can merge your changes?
> 
> @lmignon Ok

@lmignon Done

**Comment by lmignon** [comment]
@pedrobaeza How can we validate that the CLA is welll registered?

**Comment by pedrobaeza** [comment]
If the CLA is already registered in OCA instance, next commit that this contributor makes in any place will trigger the bot to post a comment saying so in all the pending PRs. But it requires at least that commit. Looking myself directly at the instance, I can confirm that Marcel has signed the CLA, so we can go on.

**Comment by lmignon** [comment]
Thank you @pedrobaeza !

**Review by lmignon — APPROVED** [review]
LGTM, all comments attended. Thank you @marcelsavegnago

**Review by pedrobaeza — APPROVED** [review]
For me as well

**Pull request merged**
