### PR TITLE
[17.0][MIG] graphql_base

### PR DESCRIPTION
**Pull request by dduarte-odoogap**

### CODE REVIEW

**Review by ccarrenoc — APPROVED** [review]

**Comment by sbidoul** [comment]
Can you preserve the commit history using the recommended procedure? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

**Comment by dduarte-odoogap** [comment]
@sbidoul sorry might have missed something, will check

**Comment by dduarte-odoogap** [comment]
@sbidoul please check

**Comment by sbidoul** [comment]
Ah, no, my bad, it was good already, since the branch was initialized from 16.0.

**Comment by sbidoul** [comment]
Please set installable=True in both manifests.

**Comment by dduarte-odoogap** [comment]
@sbidoul it's done

**Review by sbidoul — APPROVED** [review]

**Review by sbidoul — APPROVED** [review]
I did not look if something could be improved, but the change looks good, and the demo works, so :+1:

**Comment by dduarte-odoogap** [comment]
> I did not look if something could be improved, but the change looks good, and the demo works, so 👍
 
@sbidoul  we use this module a lot, will check if we can propose some improvements latter on.

**Comment by sbidoul** [comment]
Hm, that's the bot build process being confused by this types.py at the addon root. I'll need to fix it in the bot.

**Comment by yvaucher** [comment]
@sbidoul Did you had the change to look at the issue you mentioned?

**Comment by sbidoul** [comment]
Tentative fix deployed in the bot. Let's try again.

/ocabot merge nobump

**Comment by sbidoul** [comment]
Hm, not good yet.

**Comment by lmignon** [comment]
@dduarte-odoogap Can you rebase please? I would like to try to merge it again.

**Comment by sbidoul** [comment]
I'll take care of this. There is a fundamental issue with this `types.py` at the repo root that is not easily solvable. I'll try renaming that file.

**Comment by sbidoul** [comment]
Superseded by #461

**Pull request closed without merging**
