### PR TITLE
[MIG] rest_log: Migration to 16.0

### PR DESCRIPTION
**Pull request by aktiv-heli-kantawala**
* [ ] depends on #313

### CODE REVIEW

**Comment by simahawk** [comment]
@heliaktiv thanks for your work.
There are some changes to port from v14 to v15 and then here on v16. Could you please have a look?

**Comment by aktiv-heli-kantawala** [comment]
Updated already. Thank you

**Review by lmignon — CHANGES_REQUESTED** [review]
The module is still defined as ''installable': False'.... and depends on #313

**Pull request closed without merging**
